version: "3.8"
services:
  backend:
    image: "humanbeeng/streat-backend:13.4.2022.13.42.55"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      CASHFREE_TOKEN_URL: ${CASHFREE_TOKEN_URL}
      CASHFREE_CLIENT_ID: ${CASHFREE_CLIENT_ID}
      CASHFREE_CLIENT_SECRET: ${CASHFREE_CLIENT_SECRET}