version: "3.8"
services:
  backend:
    image: "humanbeeng/streats-backend:6.5.2022.17.26.28"
    
    ports:
      - "80:8080"
    
    restart: "always"
    
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      CASHFREE_TOKEN_URL: ${CASHFREE_TOKEN_URL}
      CASHFREE_CLIENT_ID: ${CASHFREE_CLIENT_ID}
      CASHFREE_CLIENT_SECRET: ${CASHFREE_CLIENT_SECRET}
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY}