name: Build & Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:


env:
  #JAVA
  JAVA_VERSION: 11
  #DOCKERHUB
  DOCKER_HUB_USERNAME: humanbeeng
  #AWS & Elastic Beanstalk
  AWS_REGION: ap-south-1
  EB_ENVIRONMENT_NAME:  streats-backend-prod
  EB_APPLICATION_NAME: streats-backend
  EB_DEPLOYMENT_PACKAGE: elb/docker-compose.yaml


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
          text: "CICD : In-progress :eyes:"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.

      - uses: actions/checkout@v2

      - name: Setup Java JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{env.JAVA_VERSION}}

      - name: Build Number
        id: build-number
        run: echo "::set-output name=BUILD_NUMBER::$(date '+%-d.%-m.%Y.%-H.%-M.%-S')"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Gradle Clean Build and Push to Dockerhub
        run: ./gradlew clean build jib -Djib.to.image=humanbeeng/streat-backend:${{steps.build-number.outputs.BUILD_NUMBER}}

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
          text: ":white_check_mark: Pushed to humanbeeng/streats-backend:${{steps.build-number.output.BUILD_NUMBER}} to Dockerhub.. https://hub.docker.com/repository/docker/humanbeeng/ecomm"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

      - name: Update and commit app version in docker-compose.yaml
        run: |
          BUILD_NUMBER=${{steps.build-number.outputs.BUILD_NUMBER}}
          echo -e "Current elb/docker-compose.yaml\n$(cat elb/docker-compose.yaml)"
          sed -i -E 's_(humanbeeng/streat-backend:)([^"]*)_\1'${BUILD_NUMBER}'_' elb/docker-compose.yaml 
          echo -e "Current elb/docker-compose.yaml\n$(cat elb/docker-compose.yaml)"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add elb/docker-compose.yaml
          git commit -m "New app version: ${BUILD_NUMBER}"
          git push

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
          text: ":elasticbeanstalk: Deployment started.. :grimacing: :crossed_fingers:"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@ebe3476a4ce991d54336935e75e78dd9d86f9408
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          application_name: ${{ env.EB_APPLICATION_NAME }}
          deployment_package: ${{ env.EB_DEPLOYMENT_PACKAGE }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          version_description: Version ${{steps.build-number.outputs.BUILD_NUMBER}} deployed via github actions ${{ github.sha }}
          wait_for_deployment: 60

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ':tada: Deployment successful http://ecommtest2-env.eba-xp3s7pmc.ap-south-1.elasticbeanstalk.com/'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
