name: Build

on:
  [push]


env:
  JAVA_VERSION: 11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{env.JAVA_VERSION}}
      - name: Gradle Clean Package
        run:
          ./gradlew clean build
